### ISSUE TITLE
请问uploads文件夹里的.gitkeep文件是什么作用？

### ISSUE THREAD

**Issue by shichzh** [hongchh/file-upload-demo#1]
请问uploads文件夹里的.gitkeep文件是什么作用？uploads文件夹用于存储上传的文件，那.gitkeep是您上传的文件吗？

**Comment by hongchh** [comment]
上传到github时会忽略空白文件夹，在uploads放.gitkeep文件只是让uploads文件夹可以顺利提交上来不被忽略，以便他人知道有这个文件夹的存在。
